tasks:
  - init: pip install -r requirements.txt
  - command: gp open 01-main.py

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
